version: '3'

services:
  consul:
    image: "consul:0.9.3"
    container_name: "consul"
    hostname: "consul"
    privileged: true
    command: >
      agent -dev -ui
        -client="0.0.0.0"
        -datacenter="dev"
        -advertise="127.0.0.1"
    restart: always
    # network_mode: host
    ports:
      - "8300-8302:8300-8302"
      - "8301-8302:8301-8302/udp"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"